/*
Crear las tablas de la BBDD de COCHES. 
Con los contenidos de las tablas, que se muestran a continuación, crea las tablas con los campos y tipo de datos adecuados; se deben indicar las claves primarias y las foráneas. Debe tener en cuenta el orden en el que se crean las tablas.

*/

-- CREAR BBDD Y PONER EN USO
CREATE DATABASE Coches;
use Coches;

-- - CREAR TABLAS
CREATE TABLE CLIENTES (
DNI INT PRIMARY KEY,
NOMBRE VARCHAR (15),
APELLIDO VARCHAR (15),
CIUDAD VARCHAR (15) );
 
CREATE TABLE COCHES (
CODCOCHE INT PRIMARY KEY,
NOMBRE VARCHAR (10),
MODELO VARCHAR (10) );

CREATE TABLE MARCAS ( 
CIFM	INT PRIMARY KEY,
NOMBRE	VARCHAR (15),
CIUDAD VARCHAR (15));

CREATE TABLE CONCESIONARIOS (
CIFC	INT PRIMARY KEY ,
NOMBRE VARCHAR (10)	,
CIUDAD VARCHAR (15));

CREATE TABLE FABRICA ( 
CIFM INT	REFERENCES MARCAS (CIFM),
CODCOCHE INT  REFERENCES COCHES (CODCOCHE),
CONSTRAINT PK_FABRICA PRIMARY KEY (CIFM, CODCOCHE));

CREATE TABLE DISTRIBUYEN ( 
CIFC INT	REFERENCES CONCESIONARIOS (CIFC),
CODCOCHE INT REFERENCES COCHES (CODCOCHE),
CANTIDAD INT ,
CONSTRAINT PK_DISTRIBUYEN PRIMARY KEY (CIFC, CODCOCHE));

CREATE TABLE VENDEN ( 
CIFC	INT	REFERENCES CONCESIONARIOS (CIFC),
DNI	INT  REFERENCES CLIENTES (DNI),
CODCOCHE	INT 	REFERENCES COCHES (CODCOCHE),
COLOR VARCHAR (10),
CONSTRAINT PK_VENDEN PRIMARY KEY (CIFC, DNI, CODCOCHE)); 
